# This workflow will run the continuous integration part of the pipeline

name: continuous_integration

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
 build-and-test-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x']
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
