# This workflow will run the continuous integration part of the pipeline

name: continuous_integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["8.0.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Run tests
        continue-on-error: true
        run: dotnet test --logger "trx;logfilename=testResults.trx"
      - name: Archive test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: api.test/TestResults/testResults.trx

  generate-test-report:
    needs: build-and-test-api
    runs-on: ubuntu-latest
    steps:
      - name: Download test result artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results
      - uses: bibipkins/dotnet-test-reporter@v1.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: "Unit Test Results"
          results-path: ./testResults.trx
          coverage-threshold: 80
